-- ============================================================
-- 015: Quotes table + posted_to_discord tracking
-- ============================================================

-- Quotes table for programming quotes shown in Discord embeds
CREATE TABLE IF NOT EXISTS quotes (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  author TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quotes_is_active ON quotes (is_active);

-- Track whether events have been posted to Discord (for recovery)
ALTER TABLE activity_events
  ADD COLUMN IF NOT EXISTS posted_to_discord BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_activity_events_unposted
  ON activity_events (posted_to_discord) WHERE posted_to_discord = FALSE;

-- ============================================================
-- Seed: 118 programming quotes from activity-bot
-- ============================================================
INSERT INTO quotes (text, author) VALUES
  ('First, solve the problem. Then, write the code.', 'John Johnson'),
  ('Code is like humor. When you have to explain it, it''s bad.', 'Cory House'),
  ('Make it work, make it right, make it fast.', 'Kent Beck'),
  ('Clean code always looks like it was written by someone who cares.', 'Robert C. Martin'),
  ('Programming isn''t about what you know; it''s about what you can figure out.', 'Chris Pine'),
  ('The best error message is the one that never shows up.', 'Thomas Fuchs'),
  ('The most disastrous thing that you can ever learn is your first programming language.', 'Alan Kay'),
  ('Simplicity is the soul of efficiency.', 'Austin Freeman'),
  ('Java is to JavaScript what car is to carpet.', 'Chris Heilmann'),
  ('Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday''s code.', 'Dan Salomon'),
  ('Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.', 'Antoine de Saint-Exupéry'),
  ('Testing leads to failure, and failure leads to understanding.', 'Burt Rutan'),
  ('Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', 'Martin Fowler'),
  ('Experience is the name everyone gives to their mistakes.', 'Oscar Wilde'),
  ('The only way to learn a new programming language is by writing programs in it.', 'Dennis Ritchie'),
  ('Programming is the art of algorithm design and the craft of debugging errant code.', 'Ellen Ullman'),
  ('Software and cathedrals are much the same — first we build them, then we pray.', 'Sam Redwine'),
  ('In order to be irreplaceable, one must always be different.', 'Coco Chanel'),
  ('Knowledge is power.', 'Francis Bacon'),
  ('Confusion is part of programming.', 'Felienne Hermans'),
  ('If debugging is the process of removing bugs, then programming must be the process of putting them in.', 'Edsger Dijkstra'),
  ('Talk is cheap. Show me the code.', 'Linus Torvalds'),
  ('Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime.', 'Muhammad Waseem'),
  ('Don''t comment bad code — rewrite it.', 'Brian Kernighan'),
  ('Before software can be reusable it first has to be usable.', 'Ralph Johnson'),
  ('It''s not a bug — it''s an undocumented feature.', 'Anonymous'),
  ('The best thing about a boolean is even if you are wrong, you are only off by a bit.', 'Anonymous'),
  ('Without requirements or design, programming is the art of adding bugs to an empty text file.', 'Louis Srygley'),
  ('One of the best programming skills you can have is knowing when to walk away for a while.', 'Oscar Godson'),
  ('Truth can only be found in one place: the code.', 'Robert C. Martin'),
  ('If you optimize everything, you will always be unhappy.', 'Donald Knuth'),
  ('Weeks of coding can save you hours of planning.', 'Anonymous'),
  ('A language that doesn''t affect the way you think about programming is not worth knowing.', 'Alan Perlis'),
  ('The computer was born to solve problems that did not exist before.', 'Bill Gates'),
  ('Walking on water and developing software from a specification are easy if both are frozen.', 'Edward V. Berard'),
  ('It works on my machine.', 'Every Developer'),
  ('Copy-and-paste is a design error.', 'David Parnas'),
  ('Deleted code is debugged code.', 'Jeff Sickel'),
  ('It''s harder to read code than to write it.', 'Joel Spolsky'),
  ('How you look at it is pretty much how you''ll see it.', 'Rasheed Ogunlaru'),
  ('Controlling complexity is the essence of computer programming.', 'Brian Kernighan'),
  ('Computers are good at following instructions, but not at reading your mind.', 'Donald Knuth'),
  ('The function of good software is to make the complex appear to be simple.', 'Grady Booch'),
  ('Good code is its own best documentation.', 'Steve McConnell'),
  ('Don''t repeat yourself. Every piece of knowledge must have a single, unambiguous, authoritative representation within a system.', 'Andy Hunt & Dave Thomas'),
  ('Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'Bill Gates'),
  ('No matter how slow you are writing clean code, you will always be slower if you make a mess.', 'Uncle Bob Martin'),
  ('A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want.', 'Niklaus Wirth'),
  ('I''m not a great programmer; I''m just a good programmer with great habits.', 'Kent Beck'),
  ('The cheapest, fastest and most reliable components of a computer system are those that aren''t there.', 'Gordon Bell'),
  ('One of my most productive days was throwing away 1000 lines of code.', 'Ken Thompson'),
  ('When in doubt, use brute force.', 'Ken Thompson'),
  ('Premature optimization is the root of all evil.', 'Donald Knuth'),
  ('Debugging is twice as hard as writing the code in the first place.', 'Brian Kernighan'),
  ('People think that computer science is the art of geniuses but the actual reality is the opposite, just many people doing things that build on each other.', 'Donald Knuth'),
  ('Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 'John Woods'),
  ('Programs must be written for people to read, and only incidentally for machines to execute.', 'Harold Abelson'),
  ('We build our computer systems the way we build our cities: over time, without a plan, on top of ruins.', 'Ellen Ullman'),
  ('There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.', 'C.A.R. Hoare'),
  ('The most important property of a program is whether it accomplishes the intention of its user.', 'C.A.R. Hoare'),
  ('There are only two kinds of languages: the ones people complain about and the ones nobody uses.', 'Bjarne Stroustrup'),
  ('Any sufficiently advanced technology is indistinguishable from magic.', 'Arthur C. Clarke'),
  ('The art of programming is the art of organizing complexity.', 'Edsger Dijkstra'),
  ('Simplicity is prerequisite for reliability.', 'Edsger Dijkstra'),
  ('Computer science is no more about computers than astronomy is about telescopes.', 'Edsger Dijkstra'),
  ('It is not enough for code to work.', 'Robert C. Martin'),
  ('The ratio of time spent reading versus writing code is well over 10 to 1.', 'Robert C. Martin'),
  ('You can''t have great software without a great team.', 'Jim McCarthy'),
  ('Program testing can be used to show the presence of bugs, but never to show their absence.', 'Edsger Dijkstra'),
  ('To iterate is human, to recurse divine.', 'L. Peter Deutsch'),
  ('The trouble with programmers is that you can never tell what a programmer is doing until it''s too late.', 'Seymour Cray'),
  ('Software is a great combination between artistry and engineering.', 'Bill Gates'),
  ('If we want users to like our software, we should design it to behave like a likeable person.', 'Alan Cooper'),
  ('Design is not just what it looks like and feels like. Design is how it works.', 'Steve Jobs'),
  ('The purpose of software engineering is to control complexity, not to create it.', 'Pamela Zave'),
  ('Telling a programmer there''s already a library to do X is like telling a songwriter there''s already a song about love.', 'Pete Cordell'),
  ('There is no programming language — no matter how structured — that will prevent programmers from making bad programs.', 'Larry Flon'),
  ('Documentation is a love letter that you write to your future self.', 'Damian Conway'),
  ('Shipping is a feature. A really important feature. Your product must have it.', 'Joel Spolsky'),
  ('The sooner you start to code, the longer the program will take.', 'Roy Carlson'),
  ('First do it, then do it right, then do it better.', 'Addy Osmani'),
  ('Everybody in this country should learn to program a computer, because it teaches you how to think.', 'Steve Jobs'),
  ('It always takes longer than you expect, even when you take into account Hofstadter''s Law.', 'Hofstadter''s Law'),
  ('Software being Done is like lawn being Mowed.', 'Jim Benson'),
  ('The best code is no code at all.', 'Jeff Atwood'),
  ('Real programmers don''t comment their code. If it was hard to write, it should be hard to read.', 'Anonymous'),
  ('Make everything as simple as possible, but not simpler.', 'Albert Einstein'),
  ('Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.', 'Patrick McKenzie'),
  ('In programming, the hard part isn''t solving problems, but deciding what problems to solve.', 'Paul Graham'),
  ('The best performance improvement is the transition from the nonworking state to the working state.', 'J. Osterhout'),
  ('Code is like poetry; most of it shouldn''t have been written.', 'Anonymous'),
  ('A good programmer is someone who always looks both ways before crossing a one-way street.', 'Doug Linder'),
  ('Optimism is an occupational hazard of programming; feedback is the treatment.', 'Kent Beck'),
  ('Commit early, commit often.', 'Anonymous'),
  ('If you think good architecture is expensive, try bad architecture.', 'Brian Foote'),
  ('The only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room with armed guards.', 'Gene Spafford'),
  ('Software eventually and inevitably becomes legacy software.', 'Martin Fowler'),
  ('Simple things should be simple, complex things should be possible.', 'Alan Kay'),
  ('If it hurts, do it more frequently, and bring the pain forward.', 'Jez Humble'),
  ('You can mass-produce hardware; you cannot mass-produce software; you cannot mass-produce the human mind.', 'Michio Kaku'),
  ('The key to performance is elegance, not battalions of special cases.', 'Jon Bentley'),
  ('Fix the cause, not the symptom.', 'Steve Maguire'),
  ('Programming is not about typing, it''s about thinking.', 'Rich Hickey'),
  ('Fools ignore complexity. Pragmatists suffer it. Some can avoid it. Geniuses remove it.', 'Alan Perlis'),
  ('I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.', 'Bjarne Stroustrup'),
  ('When debugging, novices insert corrective code; experts remove defective code.', 'Richard Pattis'),
  ('What one programmer can do in one month, two programmers can do in two months.', 'Fred Brooks'),
  ('The Internet? Is that thing still around?', 'Homer Simpson'),
  ('Nine people can''t make a baby in a month.', 'Fred Brooks'),
  ('The value of a prototype is in the education it gives you, not in the code itself.', 'Alan Cooper'),
  ('Software is like entropy: it is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.', 'Norman Augustine'),
  ('Complexity kills. It sucks the life out of developers, it makes products difficult to plan, build, and test.', 'Ray Ozzie'),
  ('If you want to go fast, go alone. If you want to go far, go together.', 'African Proverb'),
  ('An investment in knowledge always pays the best interest.', 'Benjamin Franklin'),
  ('Programming is learned by writing programs.', 'Brian Kernighan'),
  ('Stay hungry, stay foolish.', 'Steve Jobs'),
  ('Every expert was once a beginner.', 'Helen Hayes'),
  ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill'),
  ('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt'),
  ('Code never lies, comments sometimes do.', 'Ron Jeffries');
